### ISSUE TITLE
Unknown Error can't run

### ISSUE THREAD

**Issue by BRAVO68WEB** [triethyl/melody-discord-bot#3]
I got this error install all dependence ---

(venv) root@localhost:~/mb# python3 main.py             Traceback (most recent call last):                        File "/root/mb/venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 580, in _load_from_module_spec                                                         setup(self)                                           File "/root/mb/Rythm2.py", line 1605, in setup            client.add_cog(Rythm2(client))                        File "/root/mb/venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 480, in add_cog                raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog                                                                            The above exception was the direct cause of the following exception:                                                                                                    Traceback (most recent call last):
  File "main.py", line 14, in <module>                      client.load_extension(extension)                      File "/root/mb/venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 625, in load_extension         self._load_from_module_spec(lib, name)
  File "/root/mb/venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 584, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e         discord.ext.commands.errors.ExtensionFailed: Extension 'Rythm2' raised an error: TypeError: cogs must derive from Cog

Please help..

**Comment by triethyl** [comment]
I believe it's a version issue. I'll fix it in the next commit within 24 hours.

**Comment by triethyl** [comment]
Temporarily solved by fixing version. `pip install -r requirements.txt`
